In [111]:
import numpy as np
from numpy_ringbuffer import RingBuffer
import redis, time, signal, sys
import os
import json
from sklearn.cluster import KMeans

In [130]:
def str_to_vec(s):
    return np.array([float(x) for x in s[1:-1].split(' ')])

def key_to_vec(r, key_name):
    return str_to_vec(r.get(key_name))

def vec_to_str(v):
    return '[' + ','.join(x for x in v) + ']'
def signal_handler(signal, frame):
    global runloop
    runloop = False
    print(' ... Exiting data logger')

In [48]:
def predict(x, y, z, r, x_cross = 20):
    pz = z + 4.9 * x * x
    coeffz = np.polyfit(x, pz, 1)
    coeffy = np.polyfit(x, y, 1)
    z_cross = coeffz[1] + coeffz[0] * x_cross - 4.9 * x_cross *x_cross
    y_cross = coeffy[1] + coeffy[0] * x_cross
    r.set(DES_POS_KEY, vec_to_str([x_cross, y_cross, z_cross]))
#     return np.array([x_cross, y_cross, z_cross])

In [49]:
buffersize = 10
minpts = 2

xbuff = RingBuffer(capacity=buffersize)
ybuff = RingBuffer(capacity=buffersize)
zbuff = RingBuffer(capacity=buffersize)

ptcount = 0
if True:
    ptcount = min(ptcount + 1, buffersize)
#     xbuff.append()
    if ptcount > minpts:
        xp = np.array(xbuff[:ptcount])
        yp = np.array(ybuff[:ptcount])
        zp = np.array(zbuff[:ptcount])
        predict(xp, yp, zp, redis)
        
else:
    ptcount = max(ptcount - 1, 0)

In [45]:
xm = np.array([0, 1.1, 1.9, 3.2, 4])
ts = np.array([0, 1.01, 2, 3, 4])
# dx = np.diff(x)
rx = RingBuffer(capacity = 4, dtype=np.double)
rt = RingBuffer(capacity = 4, dtype=np.double)
for x in xm:
    rx.append(x)
for t in ts:
    rt.append(t)
    
print(rx)

<RingBuffer of array([1.1, 1.9, 3.2, 4. ])>


In [110]:
xm.shape

(5,)

In [158]:
OPTI_TIMESTAMP_KEY = "sai2::optitrack::timestamp"
OPTI_POS_KEY = "sai2::optitrack::pos_single_markers"

r_server = redis.StrictRedis(host='localhost', port=6379, db=0)

num_fxpts = 0
num_vals = 1000
fpts = np.empty((num_vals, 3))

prev_time = 0
ffidx = 0

while ffidx < num_vals:
    opti_time = json.loads(r_server.get(OPTI_TIMESTAMP_KEY).decode("utf-8"))
    poslist = r_server.get(OPTI_POS_KEY).decode("utf-8").split(";")
    
    if opti_time != prev_time:
        opti_pos = json.loads("["+",".join(("".join(poslist)).split(" "))+"]")
        
        prev_time = opti_time
        num_fxpts = max(num_fxpts, len(poslist))
        
        for i in range(len(poslist)):
            fpts[ffidx,:] = opti_pos[3*i:3*(i+1)]
            ffidx += 1
            if ffidx == num_vals:
                break
            
# fpts = fpts.reshape(ffidx,3)
    
kmeans = KMeans(n_clusters=num_fxpts, random_state=0).fit(fpts)
fcords = kmeans.cluster_centers_

print("fixed markers found")



fixed markers found


In [160]:
signal.signal(signal.SIGINT, signal_handler)
runloop = True
# count = 0

folder = 'opti'
if not os.path.exists(folder):
    os.makedirs(folder)

# date and time
timestamp = time.strftime("%x").replace('/','-') + '_' + time.strftime("%X").replace(':','-')

# file names
name = "cd_f10"
# name = "comp_kin_kp100_fc10"
# name = 'k50_comp_kin_fc5'

# open files
file = open(folder + '/' + name + '_' + timestamp,'w')
    
while(runloop):
    opti_time = json.loads(r_server.get(OPTI_TIMESTAMP_KEY).decode("utf-8"))
    poslist = r_server.get(OPTI_POS_KEY).decode("utf-8").split(";")
    
    if opti_time != prev_time:
        opti_pos = json.loads("["+",".join(("".join(poslist)).split(" "))+"]")
        
        for i in range(len(poslist)):
            pos = np.array(opti_pos[3*i:3*(i+1)]).reshape(1,3)
            dist = np.linalg.norm((pos - fcords), axis = 1)
            if np.all(dist > 0.1):
                print(pos)


[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 0.929124 -0

[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.976259 -1.079369 -2.743068]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.976259 -1.079369 -2.743068]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 1.976194 -1.078992 -2.74324 ]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 1.976194 -1.078992 -2.74324 ]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 1.976194 -1.078992 -2.74324 ]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 1.976194 -1.078992 -2.74324 ]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 1.976194 -1.078992 -2.74324 ]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 1.976194 -1.078992 -2.74324 ]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 1.976194 -1.078992 -2.74324 ]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 1.976194 -1.078992 -2.74324 ]]
[[ 0.929124 -0.54856  -1.072433]]
[[ 1.976194 -1.078992 -2.74324 ]]
[[ 0.929115 -0.548448 -1.072505]]
[[ 0.929115 -0.548448 -1.072505]]
[[ 0.929115 -0.548448 -1.072505]]
[[ 0.929115 -0.548448 -1.072505]]
[[ 0.929115 -0.548448 -1.072505]]
[[ 0.929115 -0.548448 -1.072505]]
[[ 0.929115 -0.548448 -1.072505]]
[[ 0.929115 -0

[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0

[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.976082 -1.078812 -2.743102]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.976082 -1.078812 -2.743102]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.976082 -1.078812 -2.743102]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.976082 -1.078812 -2.743102]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.976082 -1.078812 -2.743102]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.976082 -1.078812 -2.743102]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.976082 -1.078812 -2.743102]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.976082 -1.078812 -2.743102]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.976082 -1.078812 -2.743102]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.976082 -1.078812 -2.743102]]
[[ 0.929115 -0.548448 -1.072505]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929115 -0.548448 -1.072505]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929115 -0.548448 -1.072505]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929115 -0.548448 -1.072505]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929115 -0.548448 -1.072505]]
[[ 1.975795 -1

[[ 0.929057 -0.548514 -1.072401]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929057 -0.548514 -1.072401]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929057 -0.548514 -1.072401]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929057 -0.548514 -1.072401]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929057 -0.548514 -1.072401]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929057 -0.548514 -1.072401]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929057 -0.548514 -1.072401]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929057 -0.548514 -1.072401]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0

[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0

[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1.078903 -2.742562]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 1.975795 -1

[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0.548533 -1.07243 ]]
[[ 0.929074 -0

In [140]:
[[ 0.623062 -0.721789 -0.540295]]
[[ 0.623062 -0.721789 -0.540295]]
[[ 0.623062 -0.721789 -0.540295]]
[[ 0.623062 -0.721789 -0.540295]]
[[ 0.623068 -0.721773 -0.540314]]
[[ 0.623068 -0.721773 -0.540314]]
[[ 0.623068 -0.721773 -0.540314]]
[[ 0.623068 -0.721773 -0.540314]]
[[ 0.623068 -0.721773 -0.540314]]
[[ 0.623068 -0.721773 -0.540314]]



array([[ 0.76475558, -1.39660123, -0.13583848],
       [ 1.9484642 , -1.11358273, -2.80404456],
       [ 0.95339527, -0.37737727, -0.91167677],
       [ 0.95338377, -1.2960896 , -0.45333186],
       [ 0.69487697, -1.29385529, -0.37603391],
       [ 1.02487883, -1.39849526, -0.21458354]])

In [159]:
fcords

array([[ 2.06736783, -1.09452638, -2.88385868],
       [ 0.69516001, -1.29370887, -0.3759126 ],
       [ 1.02484512, -1.39841353, -0.21402795],
       [ 0.76505282, -1.39675571, -0.13596366],
       [ 0.9532663 , -1.29595934, -0.45327118]])